**4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**

In [7]:
import numpy as np
print(np.__version__)
a = np.zeros(10)
a[6] = 11
print(a)

1.16.5
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**5. Write a NumPy program to create an array with values ranging from 12 to 38.**

In [14]:
b = np.arange(12,39)
print(b)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


**6. Write a NumPy program to reverse an array (first element becomes last).**

In [12]:
b = np.arange(12,39)
b = b[::-1]
print(b)

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


**7. Write a NumPy program to convert an array to a float type.**

In [18]:
b = np.arange(12,39)
print(b)

c = np.float64(b)
print(c)
print(type(c))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.
 30. 31. 32. 33. 34. 35. 36. 37. 38.]
<class 'numpy.ndarray'>


**8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**

In [21]:
d = np.ones((6,6))
d[1:-1,1:-1] = 0
print(d)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


**9. Write a NumPy program to add a border (filled with 0's) around an existing array.**

In [28]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**

In [33]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**11. Write a NumPy program to convert a list and tuple into arrays.**

In [44]:
a = ['a','b']
print(type(a))
b = ('a','b')
print(type(b))

c = np.array(a)
print(c)
print(type(c))
d = np.array(b)
print(d)
print(type(d))

<class 'list'>
<class 'tuple'>
['a' 'b']
<class 'numpy.ndarray'>
['a' 'b']
<class 'numpy.ndarray'>


**12. Write a NumPy program to append values to the end of an array.**

In [54]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


**13. Write a NumPy program to create an empty and a full array.**

In [63]:
a = np.array([])
print(a)
print(type(a))
b = np.random.random(10)
print(b)

[]
<class 'numpy.ndarray'>
[0.35389003 0.43114674 0.18682129 0.43955723 0.96005713 0.67249544
 0.81368405 0.89704053 0.61444674 0.55554468]


**14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. Sample Array [0, 12, 45.21 ,34, 99.91].**

In [65]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


**15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.**

In [66]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


**16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.**

In [70]:
d = np.array([1,17,13,105])

print(d.size)
print(d.itemsize)
print(d.nbytes)

4
4
16


**17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.**