In [2]:
import numpy as np
import pandas as pd

**Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.**

In [3]:
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


**Write a Pandas program to convert a Panda module Series to Python list and it’s type.**

In [8]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list: ",ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list:  [2, 4, 6, 8, 10]
<class 'list'>


**Write a Pandas program to add, subtract, multiple and divide two Pandas Series.**

In [9]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


**5. Write a Python program to convert a dictionary to a Pandas series.
Original dictionary:  {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}**

In [10]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


**6. Write a Python program to convert a NumPy array to a Pandas series. NumPy array:
[10 20 30 40 50]**

In [17]:
a = [10, 20, 30, 40, 50]

a = np.array(a)
print(type(a))

a = pd.Series(a)
print(type(a))
print(a)

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int32


**7. Write a Python program to change the data type of given a column or a Series.**

In [26]:
ds1 = pd.Series([2, 4, 6, 8, 10, 8.88,'a'])
print(ds1)
print(type(ds1))
print()

ds2 = pd.to_numeric(ds1, errors='coerce')
print(ds2)

0       2
1       4
2       6
3       8
4      10
5    8.88
6       a
dtype: object
<class 'pandas.core.series.Series'>

0     2.00
1     4.00
2     6.00
3     8.00
4    10.00
5     8.88
6      NaN
dtype: float64


**8. Write a Python Pandas program to convert the first column of a DataFrame as a Series**

In [35]:
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)

s = df.iloc[:,0]
print()
print(s)
print(type(s))

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


**9. Write a Pandas program to convert a given Series to an array.**

In [37]:
ds2 = pd.Series([2, 4, 6, 8, 10])

arr = np.array(ds2)
print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


**10. Write a Pandas program to convert Series of lists to one Series.**

In [38]:
import pandas as pd
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])
print("Original Series of list")
print(s)
s = s.apply(pd.Series).stack().reset_index(drop=True)
print("One Series")
print(s)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


**11. Write a Pandas program to sort a given Series.**

In [41]:
import pandas as pd

s = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s)
print()

sort = pd.Series(s).sort_values()
print(sort)

0       100
1       200
2    python
3    300.12
4       400
dtype: object

0       100
1       200
3    300.12
4       400
2    python
dtype: object


**12. Write a Pandas program to add some data to an existing Series.**

In [42]:
import pandas as pd

s = pd.Series(['100', '200', 'python', '300.12', '400'])

new_s = s.append(pd.Series(['abhijit']))

print(new_s)

0        100
1        200
2     python
3     300.12
4        400
0    abhijit
dtype: object


**13.  Write a Pandas program to create a subset of a given series based on value and condition.**

In [43]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


**14. Write a Pandas program to change the order of index of a given series.**

In [49]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
print()
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


**15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.**

In [52]:
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])

print(np.mean(s))
print(np.std(s))
print(s.mean())
print(s.std())

5.0
3.1622776601683795
5.0
3.3166247903554


In [53]:
3.1622776601683795 - 3.3166247903554

-0.1543471301870203

**16. Write a Pandas program to get the items of a given series not present in another given series.**

In [54]:
import pandas as pd
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of sr1 not present in sr2:")
result = sr1[~sr1.isin(sr2)]
print(result)

Original Series:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


**18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.**

In [57]:
s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])

print(s.min())
print(s.median())
print(s.max())
result = np.percentile(s, q=[0, 25, 50, 75, 100])
print(result)

0
5.0
10
[ 0.   2.5  5.   7.5 10. ]


**19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.**

In [58]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
print("Original Series:")
print(num_series)
print("Frequency of each unique value of the said series.")
result = num_series.value_counts()
print(result)

Original Series:
0     0
1     2
2     2
3     3
4     2
5     9
6     3
7     7
8     4
9     1
10    0
11    1
12    2
13    2
14    7
15    8
16    1
17    8
18    2
19    0
20    2
21    2
22    9
23    3
24    7
25    1
26    5
27    8
28    2
29    6
30    2
31    2
32    1
33    4
34    6
35    3
36    6
37    8
38    6
39    3
dtype: object
Frequency of each unique value of the said series.
2    11
3     5
1     5
6     4
8     4
7     3
0     3
9     2
4     2
5     1
dtype: int64


**20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.**

In [62]:
import pandas as pd
import numpy as np
np.random.RandomState(100)
num_series = pd.Series(np.random.randint(1, 5, [15]))
print("Original Series:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'

Original Series:
0     2
1     4
2     2
3     4
4     2
5     4
6     1
7     3
8     1
9     4
10    1
11    1
12    2
13    1
14    2
dtype: int32
Top 2 Freq: 2    5
1    5
4    4
3    1
dtype: int64


**24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.**

In [63]:
import pandas as pd
series1 = pd.Series(['php', 'python', 'java', 'c#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print("\nFirst and last character of each word to upper case:")
print(result)

Original Series:
0       php
1    python
2      java
3        c#
dtype: object

First and last character of each word to upper case:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


**25. Write a Pandas program to calculate the number of characters in each word in a given series.**

In [64]:
import pandas as pd
series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x: len(x))
print("\nNumber of characters in each word in the said series:")
print(result)

Original Series:
0       Php
1    Python
2      Java
3        C#
dtype: object

Number of characters in each word in the said series:
0    3
1    6
2    4
3    2
dtype: int64


**27. Write a Pandas program to convert a series of date strings to a timeseries.**

In [65]:
import pandas as pd
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print("Original Series:")
print(date_series)
print("\nSeries of date strings to a timeseries:")
print(pd.to_datetime(date_series))

Original Series:
0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

Series of date strings to a timeseries:
0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]


In [84]:
import matplotlib.pyplot as plt
import seaborn as sns

a = [100,200,300,400,500,600,700,800,900,1000]

result = np.percentile(a, q=[25, 50, 75])

print(result)
print(np.min(a))
print(np.max(a))

[325. 550. 775.]
100
1000


**30. Write a Pandas program to filter words from a given series that contain atleast two vowels.**

In [86]:
import pandas as pd
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White','Dunk','Sink'])
print("Original Series:")
print(color_series)
print("\nFiltered words:")
result = mask = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])

Original Series:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
6      Dunk
7      Sink
dtype: object

Filtered words:
1     Green
2    Orange
4    Yellow
5     White
dtype: object
